In [1]:
!pip install nltk

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize

nltk.download('punkt')
nltk.download('stopwords')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
nltk.download("punkt_tab")
text = "Tokenization is the first step in text processing. It divides text into words or sentences."

words = word_tokenize(text)
sentences = sent_tokenize(text)


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [3]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
words = ["running", "runner", "ran", "runs"]
stemmed_words = [stemmer.stem(w) for w in words]
stemmed_words



['run', 'runner', 'ran', 'run']

In [4]:
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

words = ["running", "better", "ran", "flies"]

lemmatized_words = [lemmatizer.lemmatize(w, pos="v") for w in words]

print(lemmatized_words)


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


['run', 'better', 'run', 'fly']


In [5]:
import nltk

nltk.download('averaged_perceptron_tagger')



[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [6]:
print(nltk.data.path)

['/root/nltk_data', '/usr/nltk_data', '/usr/share/nltk_data', '/usr/lib/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']


In [7]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_r

True

In [8]:
import nltk
from nltk import pos_tag
from nltk.tokenize import word_tokenize

text = "john is running quickly."

tokens = word_tokenize(text)

pos_tags = pos_tag(tokens)

print(pos_tags)

[('john', 'NN'), ('is', 'VBZ'), ('running', 'VBG'), ('quickly', 'RB'), ('.', '.')]


In [9]:
!pip install transformers

In [10]:
from transformers import AutoTokenizer, AutoModel
import torch

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

text = "Transformers are powerful models for NLP"

inputs = tokenizer(text, return_tensors="pt")

outputs = model(**inputs)

print(outputs.last_hidden_state.shape)


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


torch.Size([1, 9, 768])


In [11]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

nltk.download('stopwords')
nltk.download('punkt')

text = "NLP is a fascinating field, it helps computers understand human language."

text = text.lower()
text = text.translate(str.maketrans("", "", string.punctuation))

stop_words = set(stopwords.words('english'))

words = word_tokenize(text)

filtered_words = [word for word in words if word not in stop_words]

print(filtered_words)


['nlp', 'fascinating', 'field', 'helps', 'computers', 'understand', 'human', 'language']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [12]:
from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = "Once upon a time in a small village,"

generated = generator(
    prompt,
    max_length=50,
    num_return_sequences=1,
    no_repeat_ngram_size=2,
    top_k=50,
    top_p=0.95,
    temperature=0.8,
    do_sample=True,
)

print(generated[0]["generated_text"])


Device set to use cpu
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


Once upon a time in a small village, the young girl stood on a tree and fell in love with a bear and was taken to a village to be raped by her father. She also gave birth to two other girls who would be in the same


In [13]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis", model="bert-base-uncased")

texts = [
    "I love using transformers for NLP tasks!",
    "I hate waiting for my code to run."
]

results = classifier(texts)

for text, result in zip(texts, results):
    print(f"Text: {text}")
    print(f"Label: {result['label']} (Score: {result['score']:.4f})")


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Device set to use cpu


Text: I love using transformers for NLP tasks!
Label: LABEL_0 (Score: 0.5239)
Text: I hate waiting for my code to run.
Label: LABEL_0 (Score: 0.5634)


In [14]:
import nltk
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('omw-1.4')

text = "the student are learning advanced python programming concept"

tokens = word_tokenize(text)
print("Tokens:", tokens)

pos_tags = pos_tag(tokens)
print("POS Tags:", pos_tags)

lemmatizer = WordNetLemmatizer()

def get_wordnet_pos(treebank_tag):

    if treebank_tag.startswith('J'):
        return 'a'
    elif treebank_tag.startswith('V'):
        return 'v'
    elif treebank_tag.startswith('N'):
        return 'n'
    elif treebank_tag.startswith('R'):
        return 'r'
    else:
        return 'n'

lemmatized_words = [
    lemmatizer.lemmatize(word, pos=get_wordnet_pos(tag)) for word, tag in pos_tags
]
print("Lemmatized Words:", lemmatized_words)


Tokens: ['the', 'student', 'are', 'learning', 'advanced', 'python', 'programming', 'concept']
POS Tags: [('the', 'DT'), ('student', 'NN'), ('are', 'VBP'), ('learning', 'VBG'), ('advanced', 'JJ'), ('python', 'NN'), ('programming', 'VBG'), ('concept', 'NN')]
Lemmatized Words: ['the', 'student', 'be', 'learn', 'advanced', 'python', 'program', 'concept']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [15]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "NLP is fun and exiting.",
    "Deep learning and NLP are realted field",
    "And this is the third one.",
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("Document-Term Matrix:")
print(X.toarray())

Vocabulary: ['and' 'are' 'deep' 'exiting' 'field' 'fun' 'is' 'learning' 'nlp' 'one'
 'realted' 'the' 'third' 'this']
Document-Term Matrix:
[[1 0 0 1 0 1 1 0 1 0 0 0 0 0]
 [1 1 1 0 1 0 0 1 1 0 1 0 0 0]
 [1 0 0 0 0 0 1 0 0 1 0 1 1 1]]


In [16]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

corpus = [
    "NLP is fun and exciting.",
    "Deep learning and NLP are related fields.",
    "And this is the third one.",
]

count_vectorizer = CountVectorizer()
X_count = count_vectorizer.fit_transform(corpus)

tfidf_transformer = TfidfTransformer()
X_tfidf = tfidf_transformer.fit_transform(X_count)

print("Vocabulary:", count_vectorizer.get_feature_names_out())
print("Document-Term Matrix (TF-IDF):")
print(X_tfidf.toarray())


Vocabulary: ['and' 'are' 'deep' 'exciting' 'fields' 'fun' 'is' 'learning' 'nlp' 'one'
 'related' 'the' 'third' 'this']
Document-Term Matrix (TF-IDF):
[[0.31544415 0.         0.         0.53409337 0.         0.53409337
  0.40619178 0.         0.40619178 0.         0.         0.
  0.         0.        ]
 [0.2425937  0.41074684 0.41074684 0.         0.41074684 0.
  0.         0.41074684 0.31238356 0.         0.41074684 0.
  0.         0.        ]
 [0.26607496 0.         0.         0.         0.         0.
  0.34261996 0.         0.         0.45050407 0.         0.45050407
  0.45050407 0.45050407]]


In [17]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

corpus = [
    "NLP is fun and exciting.",
    "Deep learning and NLP are related fields.",
    "And this is the third one.",
]

count_vectorizer = CountVectorizer()
X_count = count_vectorizer.fit_transform(corpus)

tfidf_transformer = TfidfTransformer()
X_tfidf = tfidf_transformer.fit_transform(X_count)

print("Vocabulary:", count_vectorizer.get_feature_names_out())
print("Document-Term Matrix (TF-IDF):")
print(X_tfidf.toarray())


Vocabulary: ['and' 'are' 'deep' 'exciting' 'fields' 'fun' 'is' 'learning' 'nlp' 'one'
 'related' 'the' 'third' 'this']
Document-Term Matrix (TF-IDF):
[[0.31544415 0.         0.         0.53409337 0.         0.53409337
  0.40619178 0.         0.40619178 0.         0.         0.
  0.         0.        ]
 [0.2425937  0.41074684 0.41074684 0.         0.41074684 0.
  0.         0.41074684 0.31238356 0.         0.41074684 0.
  0.         0.        ]
 [0.26607496 0.         0.         0.         0.         0.
  0.34261996 0.         0.         0.45050407 0.         0.45050407
  0.45050407 0.45050407]]


In [18]:
import spacy

nlp = spacy.load("en_core_web_sm")

text = "Apple is looking to buy a startup in San Francisco for $1 billion."

doc = nlp(text)

for ent in doc.ents:
    print(f"Entity: {ent.text}, Label: {ent.label_}")


Entity: Apple, Label: ORG
Entity: San Francisco, Label: GPE
Entity: $1 billion, Label: MONEY


In [19]:
from textblob import TextBlob

text = "I love this product! It's amazing."

blob = TextBlob(text)
print('sentiment polarity:',blob.sentiment.polarity)

sentiment polarity: 0.6125


In [20]:
from transformers import pipeline
translater = pipeline("translation_en_to_fr")
text = "I love this product! It's amazing."
translated_text = translater(text, max_length=40)[0]["translation_text"]
print(translated_text)

No model was supplied, defaulted to google-t5/t5-base and revision a9723ea (https://huggingface.co/google-t5/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


J'adore ce produit, c'est fantastique.


In [21]:
from transformers import pipeline
summarizer = pipeline("summarization")
text = "Natural Language refers to the language that humans use for everyday communication, as opposed to computer programming languages. It encompasses spoken, written, or signed forms of language and includes all the nuances, idioms, and rules that humans intuitively understand."
summary = summarizer(text, max_length=100, min_length=30, do_sample=False)[0]["summary_text"]
print(summary)

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu
Your max_length is set to 100, but your input_length is only 50. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=25)


 Natural Language is spoken, written, or signed forms of language . Includes all the nuances, idioms, and rules that humans intuitively understand .


In [22]:
!pip install boto3


In [23]:
!pip install awscli


In [24]:
!aws configure sso


Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument subcommand: Invalid choice, valid choices are:

list                                     | get                                     
set                                      | add-model                               
